version: "3.1"
services:
  downloader:
    build: "downloader"
    volumes:
      - ".:/work"
    working_dir: "/work"
    command: "wget --timestamping --directory-prefix=dist -i sources.lst"
  builder:
    build: "builder"
    volumes:
      - ".:/work"
    working_dir: "/work"
    command: "./build sources.lst"
